from typing import Any

def validate_not_empty(value: Any) -> bool: ...

def validate_date(date_value: Any) -> bool: ...

def validate_email(email: Any) -> bool: ...

def validate_number(num: Any) -> bool: ...

def validate_file(file: Any, tipos: list[str]) -> bool: ...

def validar_riesgo(valor: Any) -> bool: ...
